name: Web开发

on:
  push:
    branches:
      - main
    paths:
      - "web开发/**"

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Deploy
        run: rsync -avhrz --delete ./web开发/ /srv/archive/uni/web开发/
